dictionary = {'każdego': ' all ',
              'kazdego': ' all ',
              'podzbiór': ' subset',
              'podzbior': ' subset',
              'przynależy': ' member',
              'przynalezy': ' member',
              'należy': ' member',
              'nalezy': ' member',
              'i': ' ^ ',
              'lub': ' v ',
              'alternatywa': ' | ',
              'koniunkcja': ' & ',
              'potęgi': ' ^ ',
              'potegi': ' ^ ',
              'zanegowane': "'",
              'nie': '-',
              'negacja': '-',
              'razy': ' * ',
              'pomnożone': ' * ',
              'pomnozone': ' * ',
              'plus': ' + ',
              'minus': ' - ',
              'dzielone': ' / ',
              'podzielone': ' / ',
              'to': ' -> ',
              'równoważne': ' <-> ',
              'rownowazne': ' <-> ',
              'istnieje': ' exists ',
              'mniejsze': ' < ',
              'większe': ' > ',
              'wieksze': ' > ',
              'równe': ' = ',
              'rowne': ' = ',
              'równa': ' = ',
              'rowna': ' = ',
              'różne': ' != ',
              'rozne': ' != ',
              'wyrażenia': '\nformulas',
              'wyrazenia': '\nformulas',
              'wzory': '\nformulas',
              'założenia': 'assumptions',
              'zalozenia': 'assumptions',
              'cele': 'goals',
              'koniec': 'end_of_list',
              'przypisz': 'assign',
              'czas': 'max_seconds',
              'pamięć': 'max_megs',
              'klauzul': 'max_given'}


rm_list = ['wyrażeń', 'wyrazen', 'logicznie', 'logiczny', 'sie', 'się',
           'dla', 'do', 'jeżeli', 'jezeli', 'jeśli', 'jesli', 'od', 'jest', 'przez',
           'listy', 'takie', 'bądź', 'badz', 'maksymalny', 'maksymalna', 'maksymalnie']
